# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220030e7e344c30296702675e7bec99451d5f7c57c801f12b06139b864ba319d604";
    path = fetchzip {
      url = "https://github.com/unicode-org/icu/archive/2d029329c82c7792b985024b2bdab5fc7278fbc8.tar.gz";
      hash = "sha256-0BxO5qd7u/rQ3wwC/u3PqO6XKThCB+srmangomc0Jng=";
    };
  }
  {
    name = "1220167769a6af6a028d03462b98c6acee666460e927d185b9a6b726bed72a0f0541";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/boringssl.zig/archive/a5edd8c3a782d938c38ba0c307a283cda55be0f9.tar.gz";
      hash = "sha256-RCrwwqpBjRg9Q1r8HTX/KjUMR77eMMjx9lm/LymQQmw=";
    };
  }
  {
    name = "12201cad8e77deaaa1702718e70346a30f4b54d169e9152a696621d098edb093d4f3";
    path = fetchzip {
      url = "https://github.com/google/boringssl/archive/2635bedc5d12407e4e78f2250d9c8c534954e045.tar.gz";
      hash = "sha256-ZrOk7GUTMBD6Mtr3Za3LcS3s23+OljRY1fJXTyqqGpk=";
    };
  }
  {
    name = "1220510a81c32e8fd2db7ef7a47eee0a65f5f058ef151d2b86213131d4deca74f0db";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/icu.zig/archive/1341bf90d54ff64511ff918a6efb297541fdbfb4.tar.gz";
      hash = "sha256-JT2u/6REN8dS7dGpmUVCBPKAsecgPxIAdAoLCY8HPi8=";
    };
  }
  {
    name = "1220c1854d7b4c2b5cbdd8ce6593c37e4bf1ac4032664735e1537c3848becb3b5834";
    path = fetchzip {
      url = "https://zlib.net/zlib-1.3.1.tar.gz";
      hash = "sha256-acY8yFzIRYbrZ2CGODoxLnZuppsP6KZy19I9Yy77pfc=";
    };
  }
  {
    name = "1220dc88c809fcc6427d1f297744c40a304843d425b180684769bae4f18bedca16f7";
    path = fetchzip {
      url = "https://github.com/dart-lang/sdk/archive/refs/tags/3.7.0-217.0.dev.tar.gz";
      hash = "sha256-SJgaTW2Xtu2TeSnJko3BUuW3QSkxkjkEM7TxvtL2ons=";
    };
  }
  {
    name = "1220ef6711b0eca9b2d71dc293af8e7fa6ad2f1df6f2921989dc146f35ee93d62a8e";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/zlib.zig/archive/950afdcab90435db0a7199d79dcfadc6d071929d.tar.gz";
      hash = "sha256-ZxWn5TPMKDsdmlsEH/bKjCimcgT3AhKPh4q/sS1k5+s=";
    };
  }
]
